### PR TITLE
[Bug] fix issue #439

### LINKED ISSUE #439: [Bug] in some cases,  err.Error() will be called when err is nil in fact, this will cause nil pointer panic
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris-operator/issues?q=is%3Aissue) and found no similar issues.

### Version

25.7.0

### What's Wrong?

err.Error() is called when err in fact is nil in some cases;  e.g. pkg/common/utils/mysql/mysql.go line 232

Image

### What You Expected?

will not panic;

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ztonny**
in some cases, err.Error() will be called when err is nil, fix it;

### What problem does this PR solve?

Issue Number: close #439 

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [x] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

File: pkg/common/utils/mysql/mysql.go [hunk 1]
```diff
@@ -232,8 +232,7 @@ func (db *DB) GetBackendsByComputeGroupId(cgid string) ([]*Backend, error) {
 			return nil, err
 		}
 		if _, ok := m[COMPUTE_GROUP_ID]; !ok {
-			klog.Errorf("GetBackendsByComputeGroupId backends tag get compute_group_name failed, tag: %s, err: %s\n", be.Tag, err.Error())
-			return nil, err
+			return nil, fmt.Errorf("GetBackendsByComputeGroupId backends tag get compute_group_name failed, tag: %s, err: no compute_group_id field found", be.Tag)
```
Comment (catpineapple) [inline pkg/common/utils/mysql/mysql.go]: 'klog.Errorf' needs to print the error log, here you need to keep using this method to print this error log

File: pkg/common/utils/resource/configmap_test.go [hunk 2]
```diff
@@ -110,7 +110,7 @@ func Test_ResolveConfigMpas(t *testing.T) {
 
 	m, err := ResolveConfigMaps(tests, dorisv1.Component_FE)
 	if err != nil || len(m) == 0 {
-		t.Errorf("resolve configmaps faild, len=%d, err=%s", len(m), err.Error())
+		t.Errorf("resolve configmaps faild, len=%d, err=%#v", len(m), err)
```
Comment (catpineapple) [inline pkg/common/utils/resource/configmap_test.go]: Try not to use %#v to print structure instances. This may cause err null pointer problems and require post-processing after checking for null.

**Review by catpineapple — COMMENTED** [review]
Please check it

**Review by catpineapple — APPROVED** [review]
LGTM
